VeriBlock/alt-integration-cpp

- include/veriblock/base58.h
- src/CMakeLists.txt
- src/crypto/base58.cpp
- test/CMakeLists.txt
- test/base58_test.cpp
Implement next features:
- base58 for serrialization/desserialization functionality
- base58 tests
> implement base58

- include/veriblock/sha256.h
- src/sha256.cpp
- test/sha256_test.cpp
- remove hmac functions
- remove sha224
> Cleanup sha256

- .github/workflows/ci.yml
- test/blockchain/CMakeLists.txt
- test/blockchain/vbk_blockchain_test.cpp
- test/storage/CMakeLists.txt
- test/storage/endorsement_storage_test.cpp
- test/storage/rocks_storage_test.cpp
- test/storage/storage_test.cpp
50+ min for slowest build -> 20 min for slowest build
> Speedup tests

- include/veriblock/blockchain/alt_block_tree.hpp
- include/veriblock/blockchain/block_index.hpp
- include/veriblock/blockchain/blocktree.hpp
- include/veriblock/blockchain/chain.hpp
- src/blockchain/alt_block_tree.cpp
- test/blockchain/CMakeLists.txt
- test/blockchain/alt_invalidation_test.cpp
- test/blockchain/btc_invalidation_test.cpp
- test/blockchain/chain_test.cpp
- test/util/pop_test_fixture.hpp
- test/util/visualize.hpp
Do not remove blocks from BlockTree when doing InvalidateBlock
> Add validity flags to BlockIndex

- include/veriblock/blockchain/alt_block_tree.hpp
- include/veriblock/blockchain/block_index.hpp
- include/veriblock/blockchain/blocktree.hpp
- include/veriblock/blockchain/pop/fork_resolution.hpp
- include/veriblock/blockchain/pop/vbk_block_tree.hpp
- include/veriblock/entities/altblock.hpp
- include/veriblock/entities/btcblock.hpp
- include/veriblock/entities/vbkblock.hpp
- src/blockchain/pop/vbk_block_tree.cpp
`toPrettyString` returns string representation of item. It has been added to all major items, so that debug becomes easier.
Example of printing AltTree from scenario 1
```
AltTree{valid=101, failed=2
{valid=
AltBlockIndex{height=100, hash=8d836f642834ccd0af789a7843f6614e1eec6e847d062fc421680abad3d04160, prev=ee22bde8d7a4c567a87aacc9c9cb5ce90b288b20659197ab471b3946996bc687, endorsedBy=0, containsEndorsements=0}
AltBlockIndex{height=99, hash=ee22bde8d7a4c567a87aacc9c9cb5ce90b288b20659197ab471b3946996bc687, prev=8170f03dfab5e7dc9004b544214e1f92203fcca2153d067746b6848dfe7d3280, endorsedBy=0, containsEndorsements=0}
AltBlockIndex{height=98, hash=8170f03dfab5e7dc9004b544214e1f92203fcca2153d067746b6848dfe7d3280, prev=5d39774bbc8ac5a9e2da1dd9b41d99db71d1203a82d570646209b00c4748f9a4, endorsedBy=0, …
```
> Add toPrettyString

- .github/workflows/ci.yml
- include/veriblock/blob.hpp
- include/veriblock/blockchain/alt_block_tree.hpp
- include/veriblock/blockchain/base_block_tree.hpp
- include/veriblock/blockchain/block_index.hpp
- include/veriblock/blockchain/blocktree.hpp
- include/veriblock/blockchain/pop/fork_resolution.hpp
- include/veriblock/blockchain/pop/pop_state_machine.hpp
- include/veriblock/blockchain/pop/pop_utils.hpp
- include/veriblock/blockchain/pop/vbk_block_tree.hpp
- include/veriblock/blockchain/tree_algo.hpp
- include/veriblock/state_manager.hpp
- src/blockchain/alt_block_tree.cpp
- src/blockchain/pop/vbk_block_tree.cpp
- src/mempool.cpp
- test/blockchain/alt_blockchain_test.cpp
- test/blockchain/alt_invalidation_test.cpp
- test/blockchain/blockchain_test.cpp
- test/blockchain/btc_blockchain_test.cpp
- test/blockchain/btc_invalidation_test.cpp
- test/blockchain/pop/pop_context_test.cpp
- test/blockchain/vbk_blockchain_test.cpp
- test/e2e/CMakeLists.txt
- test/e2e/scenario_1.cpp
- test/e2e/scenario_3.cpp
Scenario 3 fails, and I know why - pointers pnext get invalidated after fork resolution... So, gonna merge this first, then work on https://gist.github.com/Warchant/16b610fa197c0d04d182f7b502800a26
> Add base block tree

- include/veriblock/blockchain/pop/pop_utils.hpp
- include/veriblock/entities/endorsement.hpp
- include/veriblock/entities/endorsements.hpp
- include/veriblock/entities/payloads.hpp
- src/entities/endorsements.cpp
- test/blockchain/pop/pop_vbk_fork_resolution_test.cpp
This is temporary change, until we integrate mempool in vBTC
> Allow duplicate VTBs

- .github/workflows/ci.yml
- Doxyfile
- cmake/lib.pc.in
I've added the darwin cross-compile process to ensure that we do not have any breaking changes that will affect the vBitcoin depends setup.
> adjust pkg description, add darwin cross compile to CI

- src/blockchain/pop/vbk_block_tree.cpp
- src/mock_miner.cpp
- test/blockchain/pop/pop_vbk_fork_resolution_test.cpp
- test/blockchain/pop/setstate_test.cpp
- test/rewards/poprewards_test.cpp
- test/util/pop_test_fixture.hpp
Remaining tests
```
12 - mempool_test (Failed)
15 - scenario_4 (Failed)
17 - scenario_6 (Failed)
18 - pop_payouts_e2e (Failed)
19 - scenario_0 (Failed)
25 - alt_blockchain_test (Failed)
```
> Fix pop fork resolution test

- include/veriblock/blockchain/base_block_tree.hpp
- include/veriblock/blockchain/pop/fork_resolution.hpp
- src/blockchain/alt_block_tree.cpp
- src/blockchain/pop/vbk_block_tree.cpp
- test/e2e/pop_payouts_e2e.cpp
- test/e2e/scenario_6.cpp
- test/util/pop_test_fixture.hpp
Remaining failing tests:
```
12 - mempool_test (Failed)
25 - alt_blockchain_test (Failed)
32 - setstate_test (Failed)
```
> Fix scenario 6

- include/veriblock/adapters/picojson.hpp
- include/veriblock/blob.hpp
- include/veriblock/blockchain/block_index.hpp
- include/veriblock/entities/address.hpp
- include/veriblock/entities/altblock.hpp
- include/veriblock/entities/atv.hpp
- include/veriblock/entities/btcblock.hpp
- include/veriblock/entities/merkle_path.hpp
- include/veriblock/entities/output.hpp
- include/veriblock/entities/payloads.hpp
- include/veriblock/entities/popdata.hpp
- include/veriblock/entities/publication_data.hpp
- include/veriblock/entities/vbk_merkle_path.hpp
- include/veriblock/entities/vbkblock.hpp
- include/veriblock/entities/vbkpoptx.hpp
- include/veriblock/entities/vbktx.hpp
- include/veriblock/entities/vtb.hpp
- include/veriblock/fmt.hpp
- include/veriblock/json.hpp
- include/veriblock/third_party/picojson.h
- test/entities/CMakeLists.txt
- test/entities/json_test.cpp
By default we ship header only JSON library - picojson.
If users want, they can write their own adapter to embed any other JSON library.
> Add ToJSON

- include/veriblock/blockchain/pop/fork_resolution.hpp
> setState: fix atomicity: rollback on an attempt to switch to an invalid chain

- include/veriblock/blockchain/block_index.hpp
- include/veriblock/blockchain/blocktree.hpp
- include/veriblock/blockchain/pop/pop_state_machine.hpp
- include/veriblock/entities/altblock.hpp
- include/veriblock/entities/vbkblock.hpp
- src/blockchain/alt_block_tree.cpp
- test/blockchain/alt_invalidation_test.cpp
- test/entities/json_test.cpp
> check that all the applied blocks always form a tree and no block is double-applied or double-unapplied; optimize the un(application) for BTC

- include/veriblock/blockchain/blocktree.hpp
- include/veriblock/blockchain/btc_block_addon.hpp
- include/veriblock/blockchain/commands/addblock.hpp
- include/veriblock/blockchain/pop/vbk_block_tree.hpp
- include/veriblock/blockchain/vbk_block_addon.hpp
- include/veriblock/entities/vtb.hpp
- src/blockchain/pop/vbk_block_tree.cpp
- src/entities/vbkpoptx.cpp
- src/mock_miner.cpp
- test/blockchain/pop/pop_vbk_block_tree_test.cpp
- test/blockchain/pop/pop_vbk_fork_resolution_test.cpp
- test/e2e/pop_fr_invalid_vbk_chain.cpp
- test/e2e/scenario_8.cpp
- test/entities/json_test.cpp
Reverts VeriBlock/alt-integration-cpp#296
> Revert "VbkBlockTree: optimize addPayloads; plug the validation hole"

- include/veriblock/algorithm.hpp
- include/veriblock/blockchain/chain.hpp
- include/veriblock/entities/atv.hpp
- include/veriblock/entities/vtb.hpp
- src/entities/atv.cpp
- src/entities/vtb.cpp
- src/mempool.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/veriblock/alt-integration-cpp/351)
> Add strongly equivalency

- include/veriblock/algorithm.hpp
- include/veriblock/blockchain/chain.hpp
- include/veriblock/entities/atv.hpp
- include/veriblock/entities/vtb.hpp
- src/entities/atv.cpp
- src/entities/vtb.cpp
- src/mempool.cpp
Reverts VeriBlock/alt-integration-cpp#351
> Revert "Add strongly equivalency"

- include/veriblock/blockchain/alt_block_addon.hpp
- include/veriblock/blockchain/alt_block_tree.hpp
- include/veriblock/blockchain/block_index.hpp
- include/veriblock/blockchain/block_status.hpp
- include/veriblock/blockchain/btc_block_addon.hpp
- include/veriblock/blockchain/vbk_block_addon.hpp
- src/blockchain/alt_block_tree.cpp
- test/blockchain/alt_blockchain_test.cpp
- test/blockchain/alt_invalidation_test.cpp
- test/e2e/duplicate_atv_test.cpp
- test/e2e/pop_payouts_e2e_test.cpp
- test/e2e/scenario_9_test.cpp
- test/e2e/setstate_atomicity_test.cpp
- test/util/pop_test_fixture.hpp
> feat!(AltTree): add sync and async block validation, BLOCK_CONNECTED flag and connectedness enforcement

- include/veriblock/blockchain/alt_block_addon.hpp
- include/veriblock/blockchain/base_block_tree.hpp
- include/veriblock/blockchain/block_index.hpp
- include/veriblock/blockchain/block_status.hpp
- include/veriblock/blockchain/blocktree.hpp
- include/veriblock/blockchain/pop/fork_resolution.hpp
- include/veriblock/blockchain/pop/pop_state_machine.hpp
- src/blockchain/alt_block_tree.cpp
- src/blockchain/pop/vbk_block_tree.cpp
- test/blockchain/alt_invalidation_test.cpp
- test/blockchain/btc_invalidation_test.cpp
- test/blockchain/pop/setstate_test.cpp
- test/e2e/duplicate_atv_test.cpp
- test/e2e/pop_fr_invalid_vbk_chain_test.cpp
- test/e2e/pop_payouts_e2e_test.cpp
- test/e2e/scenario_1_test.cpp
- test/e2e/scenario_2_test.cpp
- test/e2e/scenario_3_test.cpp
- test/e2e/scenario_4_test.cpp
- test/e2e/scenario_7_test.cpp
- test/e2e/scenario_8_test.cpp
- test/e2e/scenario_9_test.cpp
- test/e2e/standalone_validation_test.cpp
- test/entities/json_test.cpp
- test/mempool_test.cpp
- test/storage/alttree_storage_test.cpp
- test/util/pop_test_fixture.hpp
> replace multiple block validity flags with a single validity level; add more asserts

- include/veriblock/blockchain/pop/fork_resolution.hpp
- test/blockchain/pop/pop_fork_resolution_test.cpp
> adjust gap handling in the reduced publication view

- include/veriblock/blockchain/pop/fork_resolution.hpp
- include/veriblock/blockchain/pop/pop_state_machine.hpp
> Add Chain overload to State Machine

- include/veriblock/blockchain/alt_block_tree.hpp
- include/veriblock/blockchain/pop/vbk_block_tree.hpp
> document the validation hole and a way to future proof the code; fill in missing invariants; minor api doc fixes

- bindings/go/api/extern.go
- bindings/go/api/pop_context.go
- bindings/go/api/pop_context_test.go
- bindings/go/entities/altblock.go
- bindings/go/entities/atv.go
- bindings/go/entities/block_index.go
- bindings/go/entities/btcblock.go
- bindings/go/entities/vbkblock.go
- bindings/go/entities/vtb.go
- bindings/go/ffi/extern.go
- bindings/go/ffi/pop_context.go
- bindings/go/ffi/utils.go
Fix IDs for alt, vtb, vbk, btc
> Fix golang IDs

- src/blockchain/alt_block_tree.cpp
> avoid exhaustive VeriBlock best chain search on removal of the temporary block in filterInvalidPayloads

- include/veriblock/entities/merkle_tree.hpp
- include/veriblock/mock_miner_2.hpp
- pypoptools/CMakeLists.txt
- pypoptools/pypopminer/miner_2.cpp
- pypoptools/pypopminer/mock_miner_test.py
- src/c/mock_miner.cpp
- src/mock_miner_2.cpp
- test/blockchain/btc_invalidation_test.cpp
- test/blockchain/pop/pop_context_test.cpp
- test/blockchain/pop/pop_vbk_block_tree_test.cpp
- test/blockchain/pop/pop_vbk_fork_resolution_test.cpp
- test/blockchain/pop/vbk_chained_add_payloads_test.cpp
- test/blockchain/temp_block_tree_test.cpp
- test/commands/atomicity_test.cpp
- test/e2e/pop_fr_invalid_vbk_chain_test.cpp
- test/e2e/scenario_1_test.cpp
- test/e2e/scenario_2_test.cpp
- test/e2e/scenario_3_test.cpp
- test/e2e/scenario_4_test.cpp
- test/e2e/scenario_5_test.cpp
- test/e2e/scenario_6_test.cpp
- test/e2e/scenario_7_test.cpp
- test/e2e/scenario_8_test.cpp
- test/e2e/scenario_9_test.cpp
- test/mempool_prioritization_test.cpp
- test/mempool_test.cpp
- test/rewards/poprewards_test.cpp
- test/storage/alttree_storage_test.cpp
- test/util/pop_test_fixture.hpp
https://track.veriblock.org/issue/ALT-365
> Refactor MockMiner

- include/veriblock/entities/vbktx.hpp
- src/entities/vbktx.cpp
- src/serde.cpp
- test/entities/vbktx_test.cpp
https://track.veriblock.org/issue/ALT-387
> ALT-387: Fix network byte size

- pypoptools/pypopminer/miner.cpp
https://track.veriblock.org/issue/ALT-389
> ALT-389: Fix mock miner test

- pypoptools/pypoptesting/framework/node.py
- pypoptools/pypoptesting/tests/__init__.py
- pypoptools/pypoptesting/tests/pop_init.py
- pypoptools/pypoptesting/tests/restart_and_sync.py
https://track.veriblock.org/issue/ALT-407
> ALT-407: Add sleep after stop in restart

- pypoptools/pypoptesting/framework/test_framework.py
https://track.veriblock.org/issue/ALT-411
> ALT-411: Add sleep after node in shutdown

- pypoptools/pypoptesting/framework/node.py
- pypoptools/pypoptesting/framework/sync_util.py
- pypoptools/pypoptesting/framework/test_framework.py
- pypoptools/pypoptesting/tests/__init__.py
- pypoptools/pypoptesting/tests/pop_activate.py
- pypoptools/pypoptesting/tests/pop_e2e.py
- pypoptools/pypoptesting/tests/pop_fork_resolution.py
- pypoptools/pypoptesting/tests/pop_init.py
- pypoptools/pypoptesting/tests/pop_mempool_getpop.py
- pypoptools/pypoptesting/tests/pop_mempool_reorg.py
- pypoptools/pypoptesting/tests/pop_mempool_sync.py
- pypoptools/pypoptesting/tests/pop_sync.py
- pypoptools/pypoptesting/tests/preflight_checks.py
- pypoptools/pypoptesting/tests/restart_and_sync.py
- pypoptools/pypoptesting/vbitcoind_node.py
https://track.veriblock.org/issue/ALT-412
> ALT-412: Make start and stop block and wait

- pypoptools/pypoptesting/framework/test_util.py
https://track.veriblock.org/issue/ALT-449
> ALT-449: Print passed tests and disable printing dots

- include/veriblock/blockchain/block_index.hpp
- include/veriblock/blockchain/pop/fork_resolution.hpp
- include/veriblock/entities/altblock.hpp
- include/veriblock/entities/btcblock.hpp
- include/veriblock/entities/vbkblock.hpp
- pypoptools/pypopminer/entities.cpp
- src/blockchain/alt_block_tree.cpp
- src/blockchain/btc_blockchain_util.cpp
- src/blockchain/mempool_block_tree.cpp
- src/blockchain/pop/vbk_block_tree.cpp
- src/blockchain/vbk_blockchain_util.cpp
- src/bootstraps.cpp
- src/entities/altblock.cpp
- src/entities/btcblock.cpp
- src/entities/vbkblock.cpp
- src/mempool_relations.cpp
- src/storage/payloads_index.cpp
- src/storage/payloads_provider.cpp
- test/blockchain/blockchain_test.cpp
- test/blockchain/chain_test.cpp
- test/blockchain/pop/pop_vbk_block_tree_test.cpp
- test/blockchain/pop/vbk_chained_add_payloads_test.cpp
- test/e2e/scenario_6_test.cpp
- test/e2e/setstate_atomicity_test.cpp
- test/entities/btcblock_test.cpp
- test/entities/json_test.cpp
- test/stateless_validation_test.cpp
- test/util/comparator_test.hpp
- test/util/pop_test_fixture.hpp
- test/util/test_utils.hpp
This is needed for C wrapper - it is easier to expose ref to already allocated member than to manage memory of bytearray in C.
> Make getHash return ref

- pypoptools/pypoptesting/tests/pop/activate.py
https://track.veriblock.org/issue/ALT-467
> ALT-467: Split PopActivateTest into 3 cases

- docs/families/btc/integration_13_setup_abfi.md
Updated with link to docker image and reorganized to move instructions for building from source to end.
> Updated doc for setting up abfi.

- include/veriblock/pop/blockchain/base_block_tree.hpp
- include/veriblock/pop/blockchain/pop/fork_resolution.hpp
- include/veriblock/pop/blockchain/pop/pop_state_machine.hpp
- include/veriblock/pop/storage/util.hpp
- src/pop/blockchain/alt_block_tree.cpp
- src/pop/blockchain/mempool_block_tree.cpp
- src/pop/blockchain/pop/vbk_block_tree.cpp
- src/pop/crypto/progpow/progpow.cpp
- src/pop/mempool.cpp
- src/pop/pop_context.cpp
- src/pop/rewards/default_poprewards_calculator.cpp
- src/pop/storage/payloads_index.cpp
Do not merge until complete. This is a sample for now just to get feedback about the direction. Is this something we want to add throughout the code?
> Added method entry logging for one file to get feedback.

- src/pop/blockchain/alt_block_tree.cpp
> Fix segfault in connectBlock due to deep recursion

- test/pop/mempool_test.cpp
issue https://github.com/VeriBlock/alt-integration-cpp/issues/890
> Test for pop mempool inclusion order

- src/pop/mempool.cpp
- test/pop/mempool_test.cpp
> Mempool cleanup bugs fix

- pypoptools/pypoptesting/tests/pop/mempool_reorg.py
needed for https://github.com/VeriBlock/vbk-ri-btc/pull/660
> Fix mempool_reorg.py test

- src/pop/stateless_validation.cpp
- test/pop/e2e/scenario_8_test.cpp
- test/pop/stateless_validation_test.cpp
Fix https://github.com/VeriBlock/alt-integration-cpp/issues/948
> Fix BtcTx issue

- include/veriblock/pop/base58.hpp
- include/veriblock/pop/base59.hpp
- include/veriblock/pop/entities/address.hpp
- include/veriblock/pop/strutil.hpp
- src/pop/base58.cpp
- src/pop/base59.cpp
- src/pop/entities/address.cpp
- test/pop/base58_test.cpp
- test/pop/base59_test.cpp
It is logging improvement to later catch https://github.com/VeriBlock/alt-integration-cpp/issues/961 issue
> Update base58/base59 decoding error logging

- include/veriblock/bfi/bitcoin/transaction.hpp
- include/veriblock/pop/blockchain/base_block_tree.hpp
- include/veriblock/pop/blockchain/blockchain_util.hpp
- include/veriblock/pop/blockchain/chain.hpp
- include/veriblock/pop/blockchain/commands/addendorsement.hpp
- include/veriblock/pop/entities/merkle_tree.hpp
- include/veriblock/pop/third_party/fmt/core.h
- include/veriblock/pop/third_party/fmt/format-inl.h
- include/veriblock/pop/third_party/fmt/format.h
- include/veriblock/pop/third_party/fmt/printf.h
- include/veriblock/pop/third_party/thread_pool/fixed_function.hpp
- src/pop/third_party/secp256k1/ecdsa_impl.hpp
- src/pop/third_party/secp256k1/eckey_impl.hpp
- src/pop/third_party/secp256k1/ecmult_gen_impl.hpp
- src/pop/third_party/secp256k1/ecmult_impl.hpp
- src/pop/third_party/secp256k1/group_impl.hpp
- src/pop/third_party/secp256k1/scalar_8x32_impl.hpp
- src/pop/third_party/secp256k1/scalar_impl.hpp
- src/pop/third_party/secp256k1/secp256k1.cpp
- src/pop/third_party/sha256.cpp
Each operand of the ! operator, the logical && or the logical || operators shall have type bool.
his rule is a strict implementation of a MISRA (Motor Industry Software Reliability Association) rule. MISRA defines best practices for developing safety-critical software. You can learn more about this rule in the MISRA documents referenced below.
If you are not concerned with MISRA compliance or with safety-critical software, you might consider using rule S867 instead ; it targets the same kind of issue for general-purpose software.
See
MISRA C++:2008, 5-3-1 - Each operand of the ! operator, the logical && or the logical || operators shall have type bool.
> Fix Sonar logical operands

- include/veriblock/pop/blockchain/alt_chain_params.hpp
- include/veriblock/pop/blockchain/btc_chain_params.hpp
- include/veriblock/pop/blockchain/payloads_index.hpp
- include/veriblock/pop/entities/address.hpp
- include/veriblock/pop/entities/merkle_tree.hpp
- include/veriblock/pop/mempool.hpp
- include/veriblock/pop/read_stream.hpp
- include/veriblock/pop/third_party/fmt/format.h
- src/pop/base58.cpp
- src/pop/blockchain/mempool_block_tree.cpp
- src/pop/blockchain/pop/vbk_block_tree.cpp
- src/pop/entities/address.cpp
- src/pop/mempool.cpp
- src/pop/mock_miner.cpp
- src/pop/third_party/secp256k1/eckey_impl.hpp
fixe the following Sonar issues:
- **A variable which is not modified shall be const qualified**
- **Limited dependence should be placed on operator precedence**
- **typedefs that indicate size and signedness should be used in place of the basic types**
- **Each operand of the ! operator, the logical && or the logical || operators shall have type bool**
> fix Sonar issues

- benchmark/mempool.cpp
Close https://github.com/VeriBlock/alt-integration-cpp/issues/986
> add Mempool_generatePopData simple bench
